version: '2'
services:
  rsyslog:
    image: kusprayitna/rsyslog:latest
    container_name: rsyslog
    ulimits:
       memlock:
          soft: -1
          hard: -1
          #mem_limit: 128m
    networks:
       - logger-net

networks:
    logger-net:
      driver: bridge

